apiVersion: extensions/v1beta1    # crowd Deployment
kind: Deployment
metadata:
  labels:
    app: crowd
  name: crowd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crowd
      name: crowd
    spec:
      containers:
        - name: crowd
          image: "atlassian/crowd:4.0.0"
          env:
            - name: ATL_TOMCAT_SECURE
              value: "true"
            - name: ATL_TOMCAT_SCHEME
              value: "https"
            - name: ATL_PROXY_PORT
              value:  "443"
            - name: ATL_PROXY_NAME
              value:  "crowd.agiletrailblazers.com"
          ports:
            - containerPort: 8095
          resources:
            limits:
              cpu: "2"
              memory: "4G"
            requests:
              cpu: "1"
              memory: "2G"
          volumeMounts:
            - name: "crowdhome"
              mountPath: /var/atlassian/application-data/crowd
      volumes:
        - name: crowdhome
          persistentVolumeClaim:
            claimName: crowd-home-pv-claim
