kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: crowd-postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: crowd-home-pv-claim
  labels:
    app: crowd
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
