global:
  slack_api_url: "https://hooks.slack.com/services/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"
route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'alert-team'
  routes:
  - match:
      alertname: InstanceDown
    receiver: 'alert-team'
  - match:
      alertname: EndpointDown
    receiver: 'alert-team'

receivers:
- name: 'alert-team'
  slack_configs:
  send_resolved: true
  - channel: "#devops"
    text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
