modules:
  http_monitor:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ['HTTP/1.1', 'HTTP/2']
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: true
      valid_status_codes: [200]
      fail_if_body_matches_regexp: ['supported endpoints are']
      tls_config:
        insecure_skip_verify: true
