global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
- job_name: Jenkins
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets: ['10.0.0.82:8080']
  metrics_path: "/jenkins/prometheus"
- job_name: Jira
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets: ['10.0.0.39:8080']
  metrics_path: "/jira/plugins/servlet/prometheus/metrics"
- job_name: BitBucket
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets: ['10.0.0.39:8095']
  metrics_path: "/bitbucket/plugins/servlet/prometheus/metrics"
- job_name: Confluence
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets: ['10.0.0.39:8090']
  metrics_path: "/confluence/plugins/servlet/prometheus/metrics"
- job_name: cadvisor
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: 'Prometheus'
  honor_timestamps: true
  scheme: http
  static_configs:
  - targets: ['10.0.0.103:9090', '10.0.0.103:9115']
  metrics_path: /metrics

- job_name: 'node'
  honor_timestamps: true
  static_configs:
  - targets: ['10.0.0.82:9100', '10.0.0.39:9100', '10.0.0.103:9100', '10.0.0.54:9100', '10.0.0.108:9100', '10.0.0.64:9100', '10.0.0.120:9100']
    labels:
      group: "pipeline-tools"

- job_name: 'Tools URL Monitoring'
  metrics_path: /probe
  params:
    module: [http_monitor]
  static_configs:
    - targets:
      - https://pilot.agiletrailblazers.com/grafana
      - https://pilot.agiletrailblazers.com/prometheus
      - https://pilot.agiletrailblazers.com/jenkins
      - https://pilot.agiletrailblazers.com/sonarqube
      - https://pilot.agiletrailblazers.com/artifactory
      - https://pilot.agiletrailblazers.com/minio
      - https://pilot.agiletrailblazers.com/kibana
#      - https://pilot.agiletrailblazers.com/elasticsearch
      - https://pilot.agiletrailblazers.com/jira
      - https://pilot.agiletrailblazers.com/confluence
      - https://pilot.agiletrailblazers.com/bitbucket
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: endpoint
    - target_label: __address__
      replacement: 10.0.0.103:9115  # The blackbox exporter's real hostname:port.

rule_files:
  - /etc/prometheus/alerts/alert.rules*.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '10.0.0.103:9093'
