version: "3.7"
services:
  jnlp-slave-jdk-11:
    build:
      context: jnlp-slave
      dockerfile: jnlp-slave-jdk-11
    container_name: jnlp-slave-jdk-11
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    command: -url http://10.0.0.217:8080/jenkins a964c1c75bc72e503370189d34eff9a7d179252f5bca880c0b86e4aa65a489bb modp_jenkins_worker_jdk-11
    logging:
      driver: fluentd
      options:
           fluentd-address: "tcp://10.0.0.108:24224"
           tag: "docker.{{.ID}}"
