version: "3.7"
services:
  jnlp-slave:
    build:
      context: jnlp-slave
      dockerfile: jnlp-slave
    container_name: jnlp-slave
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    command: -url http://10.0.0.217:8080/jenkins c63be5a60ce51faaaf4653c806c9c62c9dfed01ea058306d67fa8749cd687757 modp_jenkins_worker_2
    logging:
      driver: fluentd
      options:
           fluentd-address: "tcp://10.0.0.108:24224"
           tag: "docker.{{.ID}}"
