kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-data-pv-claim
  labels:
    app: nexus
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi