apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  labels:
    app: nexus-service
spec:
  ports:
    - name: nexus
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: docker
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: nexus
  sessionAffinity: None
  type: ClusterIP

