apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  labels:
    app: jenkins-service
spec:
  ports:
    - name: ui
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jenkins
  sessionAffinity: None
  type: ClusterIP
---
# [START jenkins_service_discovery]
apiVersion: v1
kind: Service
metadata:
  name: jenkins-discovery
  namespace: devops-tools
spec:
  selector:
    app: jenkins
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: slaves
# [END jenkins_service_discovery]
