kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home-pv-claim
  labels:
    app: jenkins
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi