kind: PersistentVolume        #Persistent Storage Volume & Claim Node 1
apiVersion: v1
metadata:
  name: confluence-home-node1-pv
  labels:
    type: local
    app: confluence
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/confluencedc-home/confluence-node1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: confluence-home-node1-pv-claim
  labels:
    app: confluence
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume        #Persistent Storage Volume & Claim Node 2
apiVersion: v1
metadata:
  name: confluence-home-node2-pv
  labels:
    type: local
    app: confluence
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/confluencedc-home/confluence-node2"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: confluence-home-node2-pv-claim
  labels:
    app: confluence
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume        #Persistent Storage Volume & Claim Shared-Home
apiVersion: v1
metadata:
  name: confluence-shared-home-pv
  labels:
    type: local
    app: confluence
spec:
  storageClassName: gp2
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/confluencedc-home/confluence-shared-home"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: confluence-shared-home-pv-claim
  labels:
    app: confluence
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
