kind: PersistentVolume        #Persistent Storage Volume & Claim Node 1
apiVersion: v1
metadata:
  name: jira-home-node1-pv
  labels:
    type: local
    app: jira
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jiradc-home/jira-node1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-home-node1-pv-claim
  labels:
    app: jira
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume        #Persistent Storage Volume & Claim Node 2
apiVersion: v1
metadata:
  name: jira-home-node2-pv
  labels:
    type: local
    app: jira
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jiradc-home/jira-node2"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-home-node2-pv-claim
  labels:
    app: jira
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume        #Persistent Storage Volume & Claim Shared-Home
apiVersion: v1
metadata:
  name: jira-shared-home-pv
  labels:
    type: local
    app: jira
spec:
  storageClassName: gp2
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jiradc-home/jira-shared-home"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-shared-home-pv-claim
  labels:
    app: jira
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi