kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
