kind: PersistentVolume        #Persistent Storage Volume & Claim Node 1
apiVersion: v1
metadata:
  name: confluence-home-node1-pv
  labels:
    type: local
    app: confluence
spec:
  storageClassName: gp2
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/confluencedc-home/confluence-node1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: confluence-home-node1-pv-claim
  labels:
    app: confluence
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolume        #Persistent Storage Volume & Claim Shared-Home
apiVersion: v1
metadata:
  name: confluence-shared-home-pv
  labels:
    type: local
    app: confluence
spec:
  storageClassName: gp2
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/confluencedc-home/confluence-shared-home"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: confluence-shared-home-pv-claim
  labels:
    app: confluence
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1    # confluence Deployment for node 1
kind: Pod
metadata:
  labels:
    app: confluence
  name: confluence-node1
spec:
  containers:
    - name: confluence-node1
      image: "agiletrailblazers/confluence-server:7.3.3"
      ports:
        - containerPort: 8090
      env:
        - name: ATL_PRODUCT_HOME_SHARED
          value: "/var/atlassian/application-data/confluence/shared-home"
        - name: ATL_CLUSTER_NAME
          value: "Confluence-cluster"
        - name: ATL_CLUSTER_TYPE
          value: "tcp_ip"
        - name: ATL_CLUSTER_NODE_NAME
          value: "confluence-node1"
      resources:
        limits:
          cpu: "4"
          memory: "8G"
        requests:
          cpu: "2"
          memory: "4G"
      volumeMounts:
        - name: "confluence-home"
          mountPath: /var/atlassian/application-data/confluence
        - name: "confluence-shared-home"
          mountPath: /var/atlassian/application-data/confluence/shared-home
  volumes:
    - name: confluence-home
      persistentVolumeClaim:
        claimName: confluence-home-node1-pv-claim
    - name: confluence-shared-home
      persistentVolumeClaim:
        claimName: confluence-shared-home-pv-claim
---
apiVersion: v1                #confluence Service
kind: Service
metadata:
  name: confluence-service
  labels:
    app: confluence-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8090
  selector:
    app: confluence
  type: LoadBalancer

---           #Provide authorization for confluence
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: confluence-k8-calls
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: confluence
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io