apiVersion: v1
kind: Service
metadata:
  name: sonar-service
  labels:
    app: sonar-service
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonar
  sessionAffinity: None
  type: ClusterIP

