apiVersion: v1                #Config Maps for PostgreSQL Configurations
kind: ConfigMap
metadata:
  name: sonarqube-postgres-config
  labels:
    app: sonar-postgres
data:
  POSTGRES_DB: sonarqubedb
  POSTGRES_USER: sonaradmin
  POSTGRES_PASSWORD: CLATB2020Admin!
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: sonarpostgredb
      volumes:
        - name: sonarpostgredb
          persistentVolumeClaim:
            claimName: sonar-postgres-pv-claim
