kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-data-pv-claim
  labels:
    app: sonar
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-postgres-pv-claim
  labels:
    app: sonar-postgres
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi